cpualei/dont-forget-the-tea

cmnds.md, package-lock.json, package.json
added new commands to cmnds.md file
=> added user and database commands, npm packages

config/database.js
=> added production object into database.js

.env.example, .envexample, app.js, config/index.js
added session secret to env file, updated indexjs
=> added session secret to env file, updated indexjs

app.js
modified session name from variable to a string
=> modified session name from variable to a string

cmnds.md, routes/lists.js, views/delete-list.pug, views/list.pug
made the edit and delete buttons for list work
=> made the edit and delete buttons for list work

views/create-task.pug, views/edit-task.pug
=> Tasks feature

app.js, routes/subtasks.js, routes/tasks.js, routes/users.js, views/delete-subtask.pug, views/edit-subtask.pug, views/list.pug, views/subtask-details.pug, views/task-details.pug
edit subtask, delete subtask, create subtask
=> edit subtask, delete subtask, create subtask

public/javascripts/taskEdit.js, public/stylesheets/taskEdit.css, routes/tasks.js, views/create-task.pug, views/layout.pug
=> Edit dom manipulation 2

public/javascripts/taskEdit.js, routes/tasks.js, views/create-task.pug
=> finished edit dom

db/migrations/20220509202449-create-task.js, public/javascripts/subtaskEdit.js, routes/tasks.js, views/login.pug
fixed duplicated tasks for different user & set up demo user login
=> fixed duplicated tasks for different user & set up demo user login

db/migrations/20220509202502-create-list.js, db/models/list.js, public/stylesheets/index.css, routes/lists.js, views/create-list.pug, views/create-task.pug, views/delete-list.pug, views/edit-list.pug, views/homepage.pug, views/layout.pug, views/list.pug, views/subtask-details.pug, views/task-details.pug
=> fixed mergin bugs

public/stylesheets/homepage.css, public/stylesheets/index.css, public/stylesheets/layout.css, views/create-list.pug, views/create-task.pug, views/edit-list.pug, views/layout.pug, views/login.pug, views/task-details.pug
made changes to forms, added white backgrounds
=> made changes to forms, added white backgrounds

public/stylesheets/index.css, views/list.pug, views/task-details.pug
=> made changes to lists page

public/stylesheets/index.css, views/create-list.pug, views/edit-list.pug
edited other list forms in lists edit page, tasks edit page
=> edited other list forms in lists edit page, tasks edit page

db/seeders/20220509231841-listSeeders.js, public/javascripts/taskDelete.js, routes/tasks.js, views/completed-list.pug, views/create-task.pug, views/list.pug, views/signup.pug, views/task-details.pug
fixed final merge bugs
delete btn works now!!
=> Final debugging

views/create-task.pug, views/task-details.pug
=> delete button fixed

public/stylesheets/index.css, public/stylesheets/layout.css, views/homepage.pug, views/login.pug, views/signup.pug
made edits to the buttons and forms
=> More css edits

public/stylesheets/index.css, views/create-task.pug, views/delete-list.pug
centered content on delete list page
=> styled delete list page

public/stylesheets/index.css, views/create-task.pug, views/delete-list.pug
fixed add task button, completed tasks button, made task content text larger/bolder
=> Fix tasks page buttons

public/stylesheets/index.css
aligned About Us link in nav bar
=> fixed About Us
